image:
  file: .gitpod.dockerfile
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: pythonenv
    init: | 
      pip install --upgrade pip
      pip install pyglet stable-baselines3[extra]
      cd rl-baselines3-zoo
      pip install -r requirements.txt
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
